name: newsletter-CD-to-ACA

on:
  # Manual trigger
  workflow_dispatch:
  # Or trigger after CI workflow completes on main branch
  workflow_run:
    workflows: ["newsletter-CI"]  # Name of your CI workflow
    branches: [main]
    types:
      - completed

env:
  IMAGE_NAME: newsletter
  CONTAINER_APP_NAME: newsletter-app
  RESOURCE_GROUP: nitishsharma-saas
  REGISTRY_NAME: nitishsharmadev

jobs:
  deploy:
    # Only run if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # this will login using the above creds, else need an explicit acr logic action with username and password
      # Only works if your Service Principal (used in AZURE_CREDENTIALS) has AcrPush
      - name: Log in to ACR
        run: az acr login --name ${{ env.REGISTRY_NAME }}

      - name: Build and push image to ACR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          context: .

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ env.REGISTRY_NAME }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}